"use client";

import Image from "next/image";
import { useRouter } from "next/navigation";
import { useMemo, useState } from "react";
import { track } from "@vercel/analytics";
import airports from "../../data/airports.json";
import { cruiseQuestions } from "../../data/cruiseQuiz";
import { structuredOrigin } from "../../lib/recommendation/travelArea";

const images = { "Tropical islands": "/quiz/ocean.jpg", "Coastal cities": "/amalfi-feature.jpg", "Dramatic landscapes": "/banff-feature.jpg", "Remote exploration": "/quiz/nature.jpg" };
const examples = { "Tropical islands": "Caribbean · South Pacific · Hawaii", "Coastal cities": "Mediterranean · Adriatic · Northern Europe", "Dramatic landscapes": "Alaska · Norway · Iceland", "Remote exploration": "Arctic · Expedition passages" };
const airportIndex = airports.map((airport) => ({ airport, search: `${airport.code} ${airport.city} ${airport.name}`.toLowerCase() }));

function AirportField({ value, onChange }) {
  const [query, setQuery] = useState(value ? `${value.city || value.airportName} (${value.airportCode})` : "");
  const [open, setOpen] = useState(false);
  const normalized = query.trim().toLowerCase();
  const matches = useMemo(() => normalized ? airportIndex.filter(({ search }) => search.includes(normalized)).sort((a, b) => Number(b.airport.scheduled) - Number(a.airport.scheduled)).slice(0, 8).map(({ airport }) => airport) : [], [normalized]);
  function choose(airport) { setQuery(`${airport.city || airport.name} (${airport.code})`); onChange(structuredOrigin(airport.code)); setOpen(false); }
  return <div className="relative"><input aria-label="Home airport or city" role="combobox" aria-expanded={open && matches.length > 0} aria-controls="cruise-airports" autoComplete="off" value={query} onFocus={() => setOpen(true)} onBlur={() => window.setTimeout(() => setOpen(false), 150)} onChange={(event) => { setQuery(event.target.value); onChange(null); setOpen(true); }} placeholder="City, airport, or code" className="w-full border-b border-black/30 bg-transparent py-5 text-xl outline-none placeholder:text-black/25 focus:border-black" />{open && normalized ? <div id="cruise-airports" className="absolute inset-x-0 top-full z-30 max-h-72 overflow-auto border border-black/15 bg-[#fbfaf7] shadow-xl">{matches.length ? matches.map((airport) => <button type="button" key={airport.code} onMouseDown={(event) => event.preventDefault()} onClick={() => choose(airport)} className="flex w-full items-center justify-between border-b border-black/10 px-5 py-4 text-left last:border-b-0 hover:bg-[#eeeae2]"><span><strong className="block text-sm font-medium">{airport.city || airport.name}</strong><span className="mt-1 block text-[10px] uppercase tracking-[0.1em] text-black/45">{airport.name} · {airport.country}</span></span><span className="text-xs font-semibold tracking-[0.14em]">{airport.code}</span></button>) : <p className="px-5 py-4 text-xs text-black/45">No matching airport found.</p>}</div> : null}</div>;
}

function Choice({ option, selected, onClick, visual }) {
  if (visual) return <button type="button" aria-pressed={selected} onClick={onClick} className={`group relative min-h-56 overflow-hidden text-left sm:min-h-72 ${selected ? "ring-2 ring-[#9b7b43] ring-offset-4 ring-offset-[#f4f1eb]" : ""}`}><Image src={images[option]} alt="" fill sizes="(min-width:1024px) 25vw, (min-width:640px) 50vw, 100vw" className="object-cover transition duration-700 group-hover:scale-[1.025]" /><span className="absolute inset-0 bg-gradient-to-t from-black/75 via-transparent to-transparent" /><span className="absolute inset-x-0 bottom-0 p-5 text-white"><strong className="block text-sm font-medium">{option}</strong><span className="mt-2 block text-[10px] uppercase tracking-[0.1em] text-white/65">{examples[option]}</span></span></button>;
  return <button type="button" aria-pressed={selected} onClick={onClick} className={`flex min-h-16 items-center justify-between border-b px-1 text-left text-lg transition sm:min-h-20 sm:text-xl ${selected ? "border-[#9b7b43] text-black" : "border-black/16 text-black/58 hover:border-black/50 hover:text-black"}`}><span>{option}</span><span className="text-sm" aria-hidden="true">{selected ? "●" : "○"}</span></button>;
}

export function CruiseQuiz() {
  const router = useRouter();
  const [step, setStep] = useState(0);
  const [answers, setAnswers] = useState({});
  const [locationState, setLocationState] = useState("");
  const question = cruiseQuestions[step];
  const selected = answers[question.id];
  const ready = question.id === "budget" ? Number(answers.budget) >= 1000 : question.id === "origin" ? Boolean(answers.originDetails?.airportCode) : Boolean(selected);
  function choose(option) { setAnswers((current) => ({ ...current, [question.id]: option })); }
  function next() { if (!ready) return; if (step < cruiseQuestions.length - 1) { setStep((current) => current + 1); window.scrollTo({ top: 0, behavior: "smooth" }); return; } const payload = { ...answers, version: 1, createdAt: new Date().toISOString() }; window.localStorage.setItem("globtrekCruiseQuiz", JSON.stringify(payload)); track("cruise_quiz_completed", { experience: payload.experience, duration: payload.duration, budget: Number(payload.budget), origin: payload.originDetails.airportCode }); router.push("/cruises/results"); }
  function useLocation() {
    if (!navigator.geolocation) { setLocationState("Location is not available in this browser. Choose an airport manually."); return; }
    setLocationState("Finding the closest airport…");
    navigator.geolocation.getCurrentPosition(async ({ coords }) => { try { const response = await fetch("/api/origin/nearest-airport", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ latitude: coords.latitude, longitude: coords.longitude }) }); const payload = await response.json(); if (!response.ok || !payload.origin) throw new Error(); setAnswers((current) => ({ ...current, originDetails: payload.origin })); setLocationState(`${payload.origin.city || payload.origin.airportName} (${payload.origin.airportCode}) selected.`); } catch { setLocationState("We couldn’t resolve that location confidently. Choose an airport manually."); } }, () => setLocationState("Location permission was not available. Choose an airport manually."), { timeout: 10000, maximumAge: 600000 });
  }
  return <section className="min-h-[calc(100svh-8rem)] px-5 py-10 sm:px-8 sm:py-16"><div className="mx-auto max-w-[1320px]"><div className="flex items-center justify-between border-b border-black/12 pb-5 text-[10px] uppercase tracking-[0.18em] text-black/45"><button type="button" onClick={() => step ? setStep(step - 1) : router.push("/cruises")} className="text-black/65">← Back</button><span>{String(step + 1).padStart(2, "0")} / {String(cruiseQuestions.length).padStart(2, "0")}</span></div><div className="pt-12 sm:pt-16"><p className="text-[10px] uppercase tracking-[0.22em] text-[#8a6b36]">{question.eyebrow}</p><h1 className="mt-5 max-w-5xl font-serif text-[clamp(3.2rem,6.2vw,7rem)] leading-[.87] tracking-[-0.055em]">{question.title}</h1>
    {question.id === "budget" ? <div className="mt-14 max-w-2xl sm:mt-20"><label className="block text-[10px] uppercase tracking-[0.18em] text-black/45" htmlFor="cruise-budget">Total trip budget · USD</label><div className="mt-4 flex items-baseline border-b border-black/35 pb-4"><span className="font-serif text-4xl text-black/40 sm:text-6xl">$</span><input id="cruise-budget" type="number" inputMode="numeric" min="1000" max="500000" step="100" autoFocus value={answers.budget || ""} onChange={(event) => setAnswers((current) => ({ ...current, budget: event.target.value }))} placeholder="5,000" className="min-w-0 flex-1 bg-transparent px-3 font-serif text-5xl tracking-[-0.05em] outline-none placeholder:text-black/18 sm:text-8xl" /></div><p className="mt-5 text-sm text-black/48">Cruise, flights or driving, port hotel, and local transport. Planning estimates are never shown as live fares.</p></div> : question.id === "origin" ? <div className="mt-14 max-w-2xl sm:mt-20"><p className="text-[10px] uppercase tracking-[0.18em] text-black/45">Enter home airport or city</p><AirportField value={answers.originDetails} onChange={(originDetails) => setAnswers((current) => ({ ...current, originDetails }))} /><button type="button" onClick={useLocation} className="mt-7 border-b border-black pb-1 text-xs font-semibold uppercase tracking-[0.08em]">Use my location</button>{locationState ? <p aria-live="polite" className="mt-4 text-xs text-black/48">{locationState}</p> : null}</div> : <div className={`mt-12 sm:mt-16 ${question.visual ? "grid gap-3 sm:grid-cols-2 lg:grid-cols-4" : "grid max-w-4xl gap-x-10 sm:grid-cols-2"}`}>{question.options.map((option) => <Choice key={option} option={option} selected={selected === option} onClick={() => choose(option)} visual={question.visual} />)}</div>}
    </div><div className="mt-14 flex justify-end border-t border-black/12 pt-6 sm:mt-20"><button type="button" disabled={!ready} onClick={next} className="inline-flex min-h-14 min-w-52 items-center justify-between bg-[#171714] px-6 text-xs font-semibold uppercase tracking-[0.09em] text-white transition disabled:cursor-not-allowed disabled:opacity-25">{step === cruiseQuestions.length - 1 ? "Reveal my journey" : "Continue"}<span aria-hidden="true">→</span></button></div></div></section>;
}
