import test from "node:test";
import assert from "node:assert/strict";
import { destinations } from "../app/data/destinations.js";
import { normalizeBudget, normalizeTravelerProfile } from "../app/lib/recommendation/travelerProfile.js";
import { buildBudgetPlan } from "../app/lib/recommendation/budgetEngine.js";
import { rankDestinations } from "../app/lib/recommendation/destinationEngine.js";
import { hotelRecommendationGroup, rankHotels, shortlistHotels } from "../app/lib/recommendation/hotelEngine.js";
import { validateItineraryTiming } from "../app/lib/recommendation/timingValidator.js";
import { buildTripEmailModel, serializeRecommendation } from "../app/lib/recommendation/tripSerializer.js";
import { importBatch, isStale, validateHotel, validCjTrackingUrl } from "../scripts/hotels/catalog-tools.mjs";
import { enrichHotel, validateEnrichment } from "../scripts/hotels/enrich-hotels.mjs";
import { HotelInventoryProvider } from "../app/lib/inventory/HotelInventoryProvider.js";
import { destinationCoverageReport, validateDestination } from "../scripts/destinations/catalog-tools.mjs";
import { rankActivities } from "../app/lib/recommendation/activityEngine.js";
import { importActivityBatch } from "../scripts/activities/catalog-tools.mjs";

const tokyo = destinations.find((item) => item.city === "TOKYO");
const bangkok = destinations.find((item) => item.city === "BANGKOK");
const base = { answers: { alive: "Cities", escape: "Slow mornings", self: "Couple", duration: "One Week", hotel: "Design hotel", luxury: "Food", discovery: 72 }, exactBudget: 4800, includedBudgetCategories: { flights: true, hotel: true, food: true, activities: true, transportation: true }, originAirport: "PDX", guestCount: "2", tripStart: "2026-10-10", tripEnd: "2026-10-17" };

for (const amount of [1000, 2500, 4800, 10000, 100000]) test(`normalizes ${amount} budget`, () => assert.equal(normalizeTravelerProfile({ ...base, exactBudget: amount }).exactBudget, amount));
test("rejects negative, NaN and absurd budgets", () => { assert.equal(normalizeBudget(-1), null); assert.equal(normalizeBudget("nope"), null); assert.equal(normalizeBudget(1000001), null); });
test("parses normal currency formatting", () => assert.equal(normalizeBudget("$4,500"), 4500));
test("normalizes complete traveler profile", () => { const profile = normalizeTravelerProfile(base); assert.equal(profile.origin, "PDX"); assert.equal(profile.tripLength, 7); assert.equal(profile.travelers, 2); assert.equal(profile.unknownness, 72); });
test("flights excluded allocate zero", () => { const input = structuredClone(base); input.includedBudgetCategories.flights = false; assert.equal(buildBudgetPlan(normalizeTravelerProfile(input), tokyo).flightEstimate.high, 0); });
test("hotel excluded allocates zero", () => { const input = structuredClone(base); input.includedBudgetCategories.hotel = false; assert.equal(buildBudgetPlan(normalizeTravelerProfile(input), tokyo).estimates.hotel.high, 0); });
for (const category of ["food", "activities", "transportation"]) test(`${category} exclusion allocates zero`, () => { const input = structuredClone(base); input.includedBudgetCategories[category] = false; assert.equal(buildBudgetPlan(normalizeTravelerProfile(input), tokyo).estimates[category].high, 0); });
test("only hotel included reserves budget for hotel", () => { const input = { ...base, includedBudgetCategories: { flights: false, hotel: true, food: false, activities: false, transportation: false } }; const plan = buildBudgetPlan(normalizeTravelerProfile(input), tokyo); assert.ok(plan.hotelBudget > 0); assert.equal(plan.estimatedTripLow, plan.estimates.hotel.low); });
test("only activities included excludes other categories", () => { const input = { ...base, includedBudgetCategories: { flights: false, hotel: false, food: false, activities: true, transportation: false } }; const plan = buildBudgetPlan(normalizeTravelerProfile(input), tokyo); assert.equal(plan.estimates.hotel.high, 0); assert.ok(plan.activitiesBudget.high > 0); });
test("traveler count scales per-person categories", () => { const one = buildBudgetPlan(normalizeTravelerProfile({ ...base, guestCount: 1 }), bangkok); const family = buildBudgetPlan(normalizeTravelerProfile({ ...base, guestCount: 4 }), bangkok); assert.ok(family.estimates.food.low >= one.estimates.food.low * 4); });
test("long trip costs more than short trip", () => { const short = buildBudgetPlan(normalizeTravelerProfile({ ...base, tripEnd: "2026-10-13" }), tokyo); const long = buildBudgetPlan(normalizeTravelerProfile({ ...base, tripEnd: "2026-10-24" }), tokyo); assert.ok(long.estimatedTripLow > short.estimatedTripLow); });
test("peak season raises Tokyo estimate", () => { const peak = buildBudgetPlan(normalizeTravelerProfile({ ...base, tripStart: "2027-04-01", tripEnd: "2027-04-08" }), tokyo); const off = buildBudgetPlan(normalizeTravelerProfile({ ...base, tripStart: "2027-02-01", tripEnd: "2027-02-08" }), tokyo); assert.ok(peak.estimates.hotel.low > off.estimates.hotel.low); });
test("cheaper destination is more feasible for low budget", () => { const profile = normalizeTravelerProfile({ ...base, exactBudget: 2500 }); assert.ok(buildBudgetPlan(profile, bangkok).budgetFeasibilityScore > buildBudgetPlan(profile, tokyo).budgetFeasibilityScore); });
test("destination ranking uses budget and preferences", () => { const ranked = rankDestinations(destinations, normalizeTravelerProfile(base)); assert.equal(ranked.length, destinations.length); assert.ok(Number.isFinite(ranked[0].destinationMatchScore)); assert.ok(ranked[0].budgetPlan); });
test("unknownness changes destination ranking", () => { const iconic = rankDestinations(destinations, normalizeTravelerProfile({ ...base, answers: { ...base.answers, discovery: 0 } })); const obscure = rankDestinations(destinations, normalizeTravelerProfile({ ...base, answers: { ...base.answers, discovery: 95 } })); assert.notEqual(iconic[0].airport, obscure[0].airport); });
test("hotel under budget outranks over-budget equivalent", () => { const profile = normalizeTravelerProfile(base); const plan = { ...buildBudgetPlan(profile, tokyo), hotelBudget: 2100 }; const hotels = [{ name: "Fit", tags: [], typicalNightlyLow: 180, typicalNightlyHigh: 220 }, { name: "Over", tags: [], typicalNightlyLow: 700, typicalNightlyHigh: 900 }]; assert.equal(rankHotels(hotels, profile, plan)[0].name, "Fit"); });
test("missing hotel price remains eligible but unknown", () => { const profile = normalizeTravelerProfile(base); const ranked = rankHotels([{ name: "Unknown", tags: [] }], profile, buildBudgetPlan(profile, tokyo)); assert.equal(ranked[0].priceKnown, false); });
test("database null hotel prices never become zero-dollar prices", () => { const profile = normalizeTravelerProfile(base); const ranked = rankHotels([{ name: "Database null", tags: [], typicalNightlyLow: null, typicalNightlyHigh: null }], profile, buildBudgetPlan(profile, tokyo)); assert.equal(ranked[0].priceKnown, false); assert.equal(ranked[0].estimatedStayLow, null); });
test("hotel ranking tolerates a temporarily missing budget plan", () => { const profile = normalizeTravelerProfile(base); assert.doesNotThrow(() => rankHotels([{ name: "Loading state", tags: [] }], profile, undefined)); });
test("stale hotel price is retained but penalized", () => { const profile = normalizeTravelerProfile(base); const plan = { ...buildBudgetPlan(profile, tokyo), hotelBudget: 2000 }; const fresh = rankHotels([{ name: "Fresh", tags: [], typicalNightlyLow: 100, typicalNightlyHigh: 200, priceLastChecked: new Date().toISOString() }], profile, plan)[0]; const stale = rankHotels([{ name: "Stale", tags: [], typicalNightlyLow: 100, typicalNightlyHigh: 200, priceLastChecked: "2020-01-01" }], profile, plan)[0]; assert.equal(stale.priceStale, true); assert.ok(fresh.budgetFit > stale.budgetFit); assert.equal(isStale("2020-01-01"), true); });
test("missing hotel image is explicit", () => { const profile = normalizeTravelerProfile(base); assert.equal(rankHotels([{ name: "No photo", tags: [] }], profile, buildBudgetPlan(profile, tokyo))[0].imageMissing, true); });
test("shortlist returns three decisions", () => { const profile = normalizeTravelerProfile(base); const hotels = [1,2,3,4].map((id) => ({ name: `H${id}`, tags: [] })); assert.equal(shortlistHotels(hotels, profile, buildBudgetPlan(profile, tokyo)).length, 3); });
test("nine-hotel pool returns three diverse recommendation groups", () => { const profile = normalizeTravelerProfile(base); const hotels = [
  ...[1,2,3].map((id) => ({ name: `Quiet ${id}`, tags: [], relaxationScore: 95, nightlifeScore: 5, centralityScore: 25, luxuryScore: 30, designScore: 35, valueScore: 75 })),
  ...[1,2,3].map((id) => ({ name: `Social ${id}`, tags: [], relaxationScore: 25, nightlifeScore: 95, centralityScore: 95, luxuryScore: 35, designScore: 45, valueScore: 70 })),
  ...[1,2,3].map((id) => ({ name: `Premium ${id}`, tags: [], relaxationScore: 55, nightlifeScore: 40, centralityScore: 65, luxuryScore: 98, designScore: 98, valueScore: 35 })),
]; const shortlisted = shortlistHotels(hotels, profile, buildBudgetPlan(profile, tokyo)); assert.equal(shortlisted.length, 3); assert.equal(new Set(shortlisted.map(hotelRecommendationGroup)).size, 3); assert.deepEqual(new Set(shortlisted.map((item) => item.descriptor)), new Set(["Our pick", "Best value", "Upgrade"])); });
test("import rejects duplicate and invalid URL", () => { const records = [{ name: "Hotel A", destinationId: "HND", provider: "booking_com_cj", bookingUrl: "https://www.booking.com/hotel/jp/a.html" }, { name: "Hotel A", destinationId: "HND", provider: "booking_com_cj", bookingUrl: "https://www.booking.com/hotel/jp/a.html" }, { name: "Bad", destinationId: "HND", provider: "booking_com_cj", bookingUrl: "https://example.com/a" }]; const report = importBatch(records, destinations); assert.equal(report.imported, 1); assert.equal(report.duplicates, 1); assert.equal(report.invalid, 1); });
test("validator flags malformed prices and coordinates", () => { const errors = validateHotel({ name: "X", destinationId: "HND", provider: "booking_com_cj", bookingComPropertyUrl: "https://www.booking.com/hotel/jp/x.html", latitude: 120, typicalNightlyLow: 500, typicalNightlyHigh: 100 }, new Set(["HND"])); assert.ok(errors.includes("invalid_latitude")); assert.ok(errors.includes("malformed_price")); });
test("CJ URL validation rejects non-CJ links", () => { assert.equal(validCjTrackingUrl("https://www.kqzyfj.com/click-101801755-17293132"), true); assert.equal(validCjTrackingUrl("https://example.com/click-1-2"), false); assert.ok(validateHotel({ name: "X", destinationId: "HND", provider: "booking_com_cj", bookingComPropertyUrl: "https://www.booking.com/hotel/jp/x.html", cjTrackingUrl: "https://example.com" }, new Set(["HND"])).includes("invalid_cj_url")); });
test("malformed AI enrichment is rejected", () => assert.equal(validateEnrichment({ luxuryScore: 101, styleTags: ["made-up"] }), false));
test("valid AI enrichment is accepted", () => { const scores = Object.fromEntries(["luxuryScore","relaxationScore","designScore","nightlifeScore","localFeelScore","familyScore","romanticScore","centralityScore","valueScore"].map((key) => [key, 50])); assert.equal(validateEnrichment({ ...scores, styleTags: ["boutique"] }), true); });
test("AI enrichment timeout is surfaced without factual fallback", async () => { await assert.rejects(() => enrichHotel({ name: "Real Hotel", city: "Tokyo", country: "Japan", description: "Supplied factual description." }, async () => { throw new Error("timeout"); }), /timeout/); });
test("timing validator catches arrival and overlap errors", () => { const result = validateItineraryTiming({ arrivalTime: "14:00", items: [{ day: 1, start: "14:30", end: "15:30" }, { day: 1, start: "15:15", end: "16:00" }] }); assert.equal(result.valid, false); assert.ok(result.errors.some((item) => item.code === "before_arrival_buffer")); assert.ok(result.errors.some((item) => item.code === "overlap_or_transport")); });
test("saved trip and email models preserve costs and links", () => { const profile = normalizeTravelerProfile(base); const budgetPlan = buildBudgetPlan(profile, tokyo); const saved = serializeRecommendation({ travelerProfile: profile, destination: tokyo, budgetPlan, bookingLinks: { hotel: "https://example.test" } }); const email = buildTripEmailModel(saved); assert.equal(email.estimatedCostBreakdown.targetBudget, 4800); assert.equal(email.bookingLinks.hotel, "https://example.test"); });
test("saved trip restores through durable JSON", () => { const profile = normalizeTravelerProfile(base); const saved = serializeRecommendation({ travelerProfile: profile, destination: tokyo, budgetPlan: buildBudgetPlan(profile, tokyo), bookingLinks: {} }); const restored = JSON.parse(JSON.stringify(saved)); assert.equal(restored.travelerProfile.exactBudget, 4800); assert.equal(restored.destination.id, "HND"); });
test("destination validator and coverage expose hollow records", () => { const valid = { id: "x", name: "X", country: "Y", nearestAirport: "ABC", latitude: 1, longitude: 2, knownnessScore: 10, costLevel: "affordable", costProfile: { typicalHotelNightLow: 1, typicalHotelNightHigh: 2, foodDailyLow: 1, foodDailyHigh: 2, activitiesDailyLow: 1, activitiesDailyHigh: 2, transportDailyLow: 1, transportDailyHigh: 2 }, seasonality: {}, climateProfile: {}, travelerTypeTags: [], interestTags: [], images: [{ imageUrl: "https://upload.wikimedia.org/x", sourcePageUrl: "https://commons.wikimedia.org/x", licenseName: "CC BY-SA 4.0", verifiedAt: new Date().toISOString() }], verifiedAt: new Date().toISOString(), verificationSource: "https://en.wikipedia.org/wiki/X" }; assert.deepEqual(validateDestination(valid), []); const report = destinationCoverageReport([valid]); assert.equal(report.totalVerifiedDestinations, 1); assert.equal(report.hotelCoverage["0"], 1); assert.equal(report.activityCoverage["0"], 1); });
test("activity ranking responds to interests and budget", () => { const profile = normalizeTravelerProfile(base); const plan = buildBudgetPlan(profile, tokyo); const ranked = rankActivities([{ name: "Food walk", category: "food", estimatedCostLow: 10, estimatedCostHigh: 20, iconicScore: 50, relaxationScore: 55 }, { name: "Luxury car", category: "luxury", estimatedCostLow: 5000, estimatedCostHigh: 6000, iconicScore: 50, relaxationScore: 55 }], profile, plan); assert.equal(ranked[0].name, "Food walk"); });
test("database null activity prices remain unknown", () => { const profile = normalizeTravelerProfile(base); const ranked = rankActivities([{ name: "Public garden", category: "nature", estimatedCostLow: null, estimatedCostHigh: null }], profile, buildBudgetPlan(profile, tokyo)); assert.equal(ranked[0].priceKnown, false); });
test("activity ranking responds to pace and season", () => { const relaxed = normalizeTravelerProfile({ ...base, answers: { ...base.answers, escape: "Slow mornings" } }); const plan = buildBudgetPlan(relaxed, tokyo); const ranked = rankActivities([{ name: "Quiet garden", category: "nature", relaxationScore: 95, energyScore: 10, seasonality: { months: [10] } }, { name: "Winter club", category: "nightlife", relaxationScore: 5, energyScore: 100, seasonality: { months: [1] } }], relaxed, plan, { month: 10 }); assert.equal(ranked[0].name, "Quiet garden"); assert.ok(ranked[0].seasonFit > ranked[1].seasonFit); });
test("coverage report uses nine-hotel and twelve-activity readiness bands", () => { const destination = { id: "d", name: "D", country: "C", knownnessScore: 50, costLevel: "moderate", recommendationReady: false, images: [{ isHero: true }], costProfile: {}, seasonality: {} }; const hotels = Array.from({ length: 9 }, (_, index) => ({ destinationId: "d", name: `H${index}`, active: true })); const activities = Array.from({ length: 12 }, (_, index) => ({ destinationId: "d", name: `A${index}`, active: true })); const report = destinationCoverageReport([destination], hotels, activities); assert.equal(report.hotelCoverage["9+"], 1); assert.equal(report.activityCoverage["12+"], 1); });
test("activity import rejects duplicates and unverified records", () => { const now = new Date().toISOString(); const baseActivity = { name: "Real museum", destinationId: "HND", category: "museums", verificationSource: "https://www.wikidata.org/wiki/Q1", verifiedAt: now }; const report = importActivityBatch([baseActivity, baseActivity, { name: "Unknown", destinationId: "HND", category: "made_up" }], new Set(["HND"])); assert.equal(report.imported, 1); assert.equal(report.rejected, 2); });
test("provider failure is explicit", async () => { await assert.rejects(() => new HotelInventoryProvider().searchHotels(), /must be implemented/); });
