-- Style and price classifications below are derived from the existing curated
-- Tokyo hotel tags. They do not represent live prices or availability.
update public.hotel_catalog set price_tier='premium', calm_score=85, energy_score=45, social_score=40, design_score=90, relaxation_score=85, nightlife_score=40, luxury_score=90, value_score=40, updated_at=now() where destination_id='HND' and normalized_name='trunk hotel yoyogi park';
update public.hotel_catalog set price_tier='premium', calm_score=30, energy_score=92, social_score=88, design_score=92, relaxation_score=30, nightlife_score=92, luxury_score=95, value_score=30, updated_at=now() where destination_id='HND' and normalized_name='the tokyo edition toranomon';
update public.hotel_catalog set price_tier='premium', calm_score=88, energy_score=35, social_score=30, design_score=70, relaxation_score=88, nightlife_score=25, luxury_score=92, value_score=35, updated_at=now() where destination_id='HND' and normalized_name='palace hotel tokyo';
update public.hotel_catalog set price_tier='premium', calm_score=90, energy_score=35, social_score=30, design_score=75, relaxation_score=90, nightlife_score=25, luxury_score=95, value_score=30, updated_at=now() where destination_id='HND' and normalized_name='mandarin oriental tokyo';
update public.hotel_catalog set price_tier='value', calm_score=85, energy_score=35, social_score=30, design_score=90, relaxation_score=85, nightlife_score=20, luxury_score=55, value_score=92, updated_at=now() where destination_id='HND' and normalized_name='muji hotel ginza';
update public.hotel_catalog set price_tier='value', calm_score=25, energy_score=94, social_score=92, design_score=85, relaxation_score=25, nightlife_score=92, luxury_score=55, value_score=90, updated_at=now() where destination_id='HND' and normalized_name='sequence miyashita park shibuya';
update public.hotel_catalog set price_tier='midrange', calm_score=88, energy_score=30, social_score=35, design_score=92, relaxation_score=88, nightlife_score=25, luxury_score=65, value_score=75, updated_at=now() where destination_id='HND' and normalized_name='hotel k5';
update public.hotel_catalog set price_tier='value', calm_score=55, energy_score=55, social_score=60, design_score=60, relaxation_score=55, nightlife_score=45, luxury_score=40, value_score=90, updated_at=now() where destination_id='HND' and normalized_name='omo5 tokyo otsuka by hoshino resorts';

insert into public.hotel_catalog (destination_id,name,normalized_name,city,country,latitude,longitude,provider,provider_property_id,price_tier,style_tags,amenity_tags,review_rating,review_count,google_place_id,google_place_match_confidence,google_place_verified,google_place_matched_at,google_place_photo_status,google_place_photo_checked_at,identity_confidence,location_confidence,provider_link_verified,photo_count,data_completeness_score,recommendation_ready,review_status,verified_at,verification_source,property_type,calm_score,energy_score,social_score,design_score,relaxation_score,nightlife_score,luxury_score,centrality_score,value_score,business_score,active)
values
('HND','Park Hotel Tokyo','park hotel tokyo','TOKYO','JAPAN',35.6630543,139.7594515,'google_places','ChIJqbHzUMKLGGAR15DTArzlkgI','midrange',array['design','art','central']::text[],array[]::text[],4.4,2628,'ChIJqbHzUMKLGGAR15DTArzlkgI',1,true,now(),'available',now(),1,1,false,5,70,true,'verified',now(),'https://maps.google.com/?cid=185463130339643607','hotel',55,45,35,85,55,30,70,85,65,70,true),
('HND','ANA InterContinental Tokyo by IHG','ana intercontinental tokyo by ihg','TOKYO','JAPAN',35.6682896,139.7408307,'google_places','ChIJSbSAbIWLGGARr4URtFXRlWk','midrange',array['central','business','social']::text[],array[]::text[],4.3,10324,'ChIJSbSAbIWLGGARr4URtFXRlWk',1,true,now(),'available',now(),1,1,false,5,70,true,'verified',now(),'https://maps.google.com/?cid=7608217311535793583','hotel',35,82,78,60,35,70,75,90,60,92,true),
('HND','Imperial Hotel Tokyo','imperial hotel tokyo','TOKYO','JAPAN',35.672454,139.7579015,'google_places','ChIJT7wVXe6LGGARpg6sWitWN8Y','premium',array['historic','central','business']::text[],array[]::text[],4.5,12740,'ChIJT7wVXe6LGGARpg6sWitWN8Y',1,true,now(),'available',now(),1,1,false,5,70,true,'verified',now(),'https://maps.google.com/?cid=14282979487433625254','hotel',60,45,35,70,60,30,92,95,35,90,true)
on conflict (destination_id,normalized_name,provider) do update set latitude=excluded.latitude,longitude=excluded.longitude,price_tier=excluded.price_tier,style_tags=excluded.style_tags,review_rating=excluded.review_rating,review_count=excluded.review_count,google_place_id=excluded.google_place_id,google_place_verified=true,identity_confidence=excluded.identity_confidence,location_confidence=excluded.location_confidence,provider_link_verified=false,photo_count=excluded.photo_count,data_completeness_score=excluded.data_completeness_score,recommendation_ready=true,review_status='verified',verified_at=excluded.verified_at,verification_source=excluded.verification_source,calm_score=excluded.calm_score,energy_score=excluded.energy_score,social_score=excluded.social_score,design_score=excluded.design_score,relaxation_score=excluded.relaxation_score,nightlife_score=excluded.nightlife_score,luxury_score=excluded.luxury_score,centrality_score=excluded.centrality_score,value_score=excluded.value_score,business_score=excluded.business_score,active=true,updated_at=now();
